### PR TITLE
Make edit buttons more visible and consistent

### LINKED ISSUE #35: UX: Edit button not obvious
I missed the edit button. It is black, the same as text. It would be nice to make it more prominent, and maybe show your events highlighted somehow so you know it's yours.

And once you click on the event, it shows the email, but there is no edit button there. I believe there should also be an edit button there.

image

### PR DESCRIPTION
**Pull request by maurayonori**
- Add yellow color to edit button in event list
- Add edit button to event detail view
- Maintain consistent styling across both views

This pull request improves the visibility of the edit button.
Closes [#35](https://github.com/DormSoup/dormsoup/issues/35)

Previous Button
https://github.com/DormSoup/dormsoup/issues/35
CleanShot 2024-11-17 at 11 29 57

After change
CleanShot 2024-11-17 at 11 30 17

CleanShot 2024-11-17 at 11 32 02
CleanShot 2024-11-17 at 11 30 45

### CODE REVIEW

**Comment by maurayonori** [comment]
@gabrc52 
I am not an MIT student, but I decided to address this issue. Since I only read the code and implemented the changes, there may be some issues with the actual behavior on the screen. I wish your project great success.

**Comment by gabrc52** [comment]
I'm really appreciative of your quick response to my issue and still impressed that you came upon our repository. My main feedback would be to choose a color with more contrast rather than yellow (based on the first screenshot), and to add the word "Edit" like the other buttons (in the second screenshot). Thanks a lot!

After that, if @lad6558 or @mitabreu don't have other comments, we can merge 🎉

**Comment by gabrc52** [comment]
I just tested it locally and it looks good. The other nit I have is that when the edit button isn't present (for events you don't have edit access to), there is a gap where the edit button would be.

image

image

**Comment by maurayonori** [comment]
Thanks for testing it in your local environment.
I have tried to accurately reflect your feedback in my development.

# Improved Event Detail Bottom Bar Layout

## Changes Made
1-1. Modified the bottom bar layout in `EventDetail.tsx` to:
  - Add "Edit" text to detail view button
   - Use `w-1/3` width for buttons when edit access is available (3-way split)
   - Use `w-1/2` width for buttons when no edit access (2-way split)
   - Adjust border and border-radius styles conditionally
1-2. 
 - Change edit button color to red for better contrast
(I'm not sure if this is the right color.)


2. Improved UI consistency:
   - Removed empty space when edit button is not present

## Technical Details
- Added conditional classes based on `event?.editable`
- Adjusted border styles using `border-x-[1px]` or `border-l-[1px]` based on layout


## Visual States
- With edit access: Like | Add to Calendar | Edit
- Without edit access: Like | Add to Calendar
- Both layouts support liked/unliked states with proper styling

CleanShot 2024-11-17 at 12 10 31
CleanShot 2024-11-17 at 12 27 36

**Review by lad6558 — APPROVED** [review]
Looks good to me. I would prefer the `hover:-translate-y-0.5` to be preserved for the pen button on the event card, but I can see some arguments that go both ways. Feel free to go ahead and merge it

**Comment by lad6558** [comment]
Also @gabrc52 thanks for testing locally and providing feedback

**Comment by lad6558** [comment]
And thanks for the support @maurayonori

**Comment by maurayonori** [comment]
@lad6558 
Thank you very much for the great review. I have incorporated the behavior you suggested. 
I also reconsidered the color change and adjusted it to make it clearer when hovering.
CleanShot 2024-11-17 at 13 35 01

**Review by lad6558 — APPROVED** [review]
Thanks for incorporating the feedback! Also love the new color-change touch. Feel free to go ahead and merge it into main

**Comment by gabrc52** [comment]
Thanks so much again! I've merged your PR 🎉. And good luck in your future endeavors!

**Pull request merged**
