### PR TITLE
added create event button

### PR DESCRIPTION
**Pull request by jsola123**
Created a button in bottom right to make a dormspam email using mailto. Button generates an outlook email with `bcc emails for all dorms, bcc'ed to dorms, [color] for bc-talk` in body, and assigns `to:`  to current user email. On Desktop it only displays in bottom right corner. In Mobile displays under filter button. 
Screenshot 2024-10-20 at 3 39 38 PM
Screenshot 2024-10-20 at 3 38 14 PM

### CODE REVIEW

**Comment by lad6558** [comment]
Hey Jazhara, really great work in getting this PR published! Literally the best PR description I've seen. There is one final thing before getting it published though... the `bcc` doesn't work.

image

Right now the bcc recipients are lumped together as one recipient. How would you find out how to make it work?

Hint: Google "mailto bcc to multiple recipients" and look at the first stackoverflow answer, or ask ChatGPT how to modify the current

**Comment by lad6558** [comment]
After you merge this feature, do you want to send a dormspam to tell everyone that they can send dormspams on DormSoup now? That would be exciting!

**Review by lad6558 — CHANGES_REQUESTED** [review]
Hey Jazhara, really great work in getting this PR published! Literally the best PR description I've seen. There is one final thing before getting it published though... the `bcc` doesn't work.

image

Right now the bcc recipients are lumped together as one recipient. How would you find out how to make it work?

Hint: Google "mailto bcc to multiple recipients" and look at the first stackoverflow answer, or ask ChatGPT, describe your situation, and ask it how to modify the current code

**Comment by jsola123** [comment]
Hi Andi,

Thanks for reviewing it so quickly. I'll probably have made more
progress/have updates later this afternoon.

Best,
Jazhara

**Comment by lad6558** [comment]
Btw do you want to add "send via DormSoup" at the end of the dormspam? (with a link to our website)

**Comment by lad6558** [comment]
This looks good! Thanks for fixing the bug. In the last team meeting we were talking about adding a "Sent via [DormSoup](https://dormsoup.mit.edu)" link at the end of the email body text, what do you think?

**Review by lad6558 — APPROVED** [review]
Looks good to me. I also added some spacing in the generated email to make it look prettier. Feel free to go ahead and click "merge".

**Pull request merged**
